// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/Compogo/db-client/repository/comparable.proto

package repository

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comparable int32

const (
	Comparable_Eq   Comparable = 0
	Comparable_Neq  Comparable = 1
	Comparable_Gt   Comparable = 2
	Comparable_Gte  Comparable = 3
	Comparable_Lt   Comparable = 4
	Comparable_Lte  Comparable = 5
	Comparable_LIKE Comparable = 6
	Comparable_IN   Comparable = 7
)

// Enum value maps for Comparable.
var (
	Comparable_name = map[int32]string{
		0: "Eq",
		1: "Neq",
		2: "Gt",
		3: "Gte",
		4: "Lt",
		5: "Lte",
		6: "LIKE",
		7: "IN",
	}
	Comparable_value = map[string]int32{
		"Eq":   0,
		"Neq":  1,
		"Gt":   2,
		"Gte":  3,
		"Lt":   4,
		"Lte":  5,
		"LIKE": 6,
		"IN":   7,
	}
)

func (x Comparable) Enum() *Comparable {
	p := new(Comparable)
	*p = x
	return p
}

func (x Comparable) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Comparable) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Compogo_db_client_repository_comparable_proto_enumTypes[0].Descriptor()
}

func (Comparable) Type() protoreflect.EnumType {
	return &file_github_com_Compogo_db_client_repository_comparable_proto_enumTypes[0]
}

func (x Comparable) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Comparable.Descriptor instead.
func (Comparable) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Compogo_db_client_repository_comparable_proto_rawDescGZIP(), []int{0}
}

var File_github_com_Compogo_db_client_repository_comparable_proto protoreflect.FileDescriptor

const file_github_com_Compogo_db_client_repository_comparable_proto_rawDesc = "" +
	"\n" +
	"8github.com/Compogo/db-client/repository/comparable.proto\x12\x1bcompogo.database.repository*Q\n" +
	"\n" +
	"Comparable\x12\x06\n" +
	"\x02Eq\x10\x00\x12\a\n" +
	"\x03Neq\x10\x01\x12\x06\n" +
	"\x02Gt\x10\x02\x12\a\n" +
	"\x03Gte\x10\x03\x12\x06\n" +
	"\x02Lt\x10\x04\x12\a\n" +
	"\x03Lte\x10\x05\x12\b\n" +
	"\x04LIKE\x10\x06\x12\x06\n" +
	"\x02IN\x10\aB2Z0github.com/Compogo/db-client/protobuf/repositoryb\x06proto3"

var (
	file_github_com_Compogo_db_client_repository_comparable_proto_rawDescOnce sync.Once
	file_github_com_Compogo_db_client_repository_comparable_proto_rawDescData []byte
)

func file_github_com_Compogo_db_client_repository_comparable_proto_rawDescGZIP() []byte {
	file_github_com_Compogo_db_client_repository_comparable_proto_rawDescOnce.Do(func() {
		file_github_com_Compogo_db_client_repository_comparable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Compogo_db_client_repository_comparable_proto_rawDesc), len(file_github_com_Compogo_db_client_repository_comparable_proto_rawDesc)))
	})
	return file_github_com_Compogo_db_client_repository_comparable_proto_rawDescData
}

var file_github_com_Compogo_db_client_repository_comparable_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Compogo_db_client_repository_comparable_proto_goTypes = []any{
	(Comparable)(0), // 0: compogo.database.repository.Comparable
}
var file_github_com_Compogo_db_client_repository_comparable_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_Compogo_db_client_repository_comparable_proto_init() }
func file_github_com_Compogo_db_client_repository_comparable_proto_init() {
	if File_github_com_Compogo_db_client_repository_comparable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Compogo_db_client_repository_comparable_proto_rawDesc), len(file_github_com_Compogo_db_client_repository_comparable_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Compogo_db_client_repository_comparable_proto_goTypes,
		DependencyIndexes: file_github_com_Compogo_db_client_repository_comparable_proto_depIdxs,
		EnumInfos:         file_github_com_Compogo_db_client_repository_comparable_proto_enumTypes,
	}.Build()
	File_github_com_Compogo_db_client_repository_comparable_proto = out.File
	file_github_com_Compogo_db_client_repository_comparable_proto_goTypes = nil
	file_github_com_Compogo_db_client_repository_comparable_proto_depIdxs = nil
}
