// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/Compogo/db-client/repository/sort_direction.proto

package repository

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortDirection int32

const (
	SortDirection_ASC  SortDirection = 0
	SortDirection_DESC SortDirection = 1
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortDirection_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Compogo_db_client_repository_sort_direction_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_github_com_Compogo_db_client_repository_sort_direction_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescGZIP(), []int{0}
}

var File_github_com_Compogo_db_client_repository_sort_direction_proto protoreflect.FileDescriptor

const file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDesc = "" +
	"\n" +
	"<github.com/Compogo/db-client/repository/sort_direction.proto\x12\x1bcompogo.database.repository*\"\n" +
	"\rSortDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01B2Z0github.com/Compogo/db-client/protobuf/repositoryb\x06proto3"

var (
	file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescOnce sync.Once
	file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescData []byte
)

func file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescGZIP() []byte {
	file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescOnce.Do(func() {
		file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDesc), len(file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDesc)))
	})
	return file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDescData
}

var file_github_com_Compogo_db_client_repository_sort_direction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Compogo_db_client_repository_sort_direction_proto_goTypes = []any{
	(SortDirection)(0), // 0: compogo.database.repository.SortDirection
}
var file_github_com_Compogo_db_client_repository_sort_direction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_Compogo_db_client_repository_sort_direction_proto_init() }
func file_github_com_Compogo_db_client_repository_sort_direction_proto_init() {
	if File_github_com_Compogo_db_client_repository_sort_direction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDesc), len(file_github_com_Compogo_db_client_repository_sort_direction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Compogo_db_client_repository_sort_direction_proto_goTypes,
		DependencyIndexes: file_github_com_Compogo_db_client_repository_sort_direction_proto_depIdxs,
		EnumInfos:         file_github_com_Compogo_db_client_repository_sort_direction_proto_enumTypes,
	}.Build()
	File_github_com_Compogo_db_client_repository_sort_direction_proto = out.File
	file_github_com_Compogo_db_client_repository_sort_direction_proto_goTypes = nil
	file_github_com_Compogo_db_client_repository_sort_direction_proto_depIdxs = nil
}
