// Code generated by "stringer -type=Comparable"; DO NOT EDIT.

package repository

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Eq-0]
	_ = x[Neq-1]
	_ = x[Gt-2]
	_ = x[Gte-3]
	_ = x[Lt-4]
	_ = x[Lte-5]
	_ = x[LIKE-6]
	_ = x[IN-7]
}

const _Comparable_name = "EqNeqGtGteLtLteLIKEIN"

var _Comparable_index = [...]uint8{0, 2, 5, 7, 10, 12, 15, 19, 21}

func (i Comparable) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Comparable_index)-1 {
		return "Comparable(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Comparable_name[_Comparable_index[idx]:_Comparable_index[idx+1]]
}
