// Code generated by "stringer -type=SortDirection -output sort_direction_string.go"; DO NOT EDIT.

package repository

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASC-0]
	_ = x[DESC-1]
}

const _SortDirection_name = "ASCDESC"

var _SortDirection_index = [...]uint8{0, 3, 7}

func (i SortDirection) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SortDirection_index)-1 {
		return "SortDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortDirection_name[_SortDirection_index[idx]:_SortDirection_index[idx+1]]
}
