// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: db-client/proto/models.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_db_client_proto_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_db_client_proto_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_db_client_proto_models_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Page) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnName    string                 `protobuf:"bytes,1,opt,name=ColumnName,proto3" json:"ColumnName,omitempty"`
	Direction     SortDirection          `protobuf:"varint,2,opt,name=Direction,proto3,enum=database.SortDirection" json:"Direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_db_client_proto_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_db_client_proto_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_db_client_proto_models_proto_rawDescGZIP(), []int{1}
}

func (x *Sort) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *Sort) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_ASC
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnName    string                 `protobuf:"bytes,1,opt,name=ColumnName,proto3" json:"ColumnName,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Comparable    Comparable             `protobuf:"varint,3,opt,name=Comparable,proto3,enum=database.Comparable" json:"Comparable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_db_client_proto_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_db_client_proto_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_db_client_proto_models_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Filter) GetComparable() Comparable {
	if x != nil {
		return x.Comparable
	}
	return Comparable_Eq
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Sorts         []*Sort                `protobuf:"bytes,2,rep,name=Sorts,proto3" json:"Sorts,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,3,rep,name=Filters,proto3" json:"Filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_db_client_proto_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_db_client_proto_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_db_client_proto_models_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *Request) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *Request) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_db_client_proto_models_proto protoreflect.FileDescriptor

const file_db_client_proto_models_proto_rawDesc = "" +
	"\n" +
	"\x1cdb-client/proto/models.proto\x12\bdatabase\x1a$db-client/proto/sort_direction.proto\x1a db-client/proto/comparable.proto\"4\n" +
	"\x04Page\x12\x16\n" +
	"\x06Number\x18\x01 \x01(\x04R\x06Number\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\rR\x05Limit\"]\n" +
	"\x04Sort\x12\x1e\n" +
	"\n" +
	"ColumnName\x18\x01 \x01(\tR\n" +
	"ColumnName\x125\n" +
	"\tDirection\x18\x02 \x01(\x0e2\x17.database.SortDirectionR\tDirection\"t\n" +
	"\x06Filter\x12\x1e\n" +
	"\n" +
	"ColumnName\x18\x01 \x01(\tR\n" +
	"ColumnName\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x124\n" +
	"\n" +
	"Comparable\x18\x03 \x01(\x0e2\x14.database.ComparableR\n" +
	"Comparable\"\x7f\n" +
	"\aRequest\x12\"\n" +
	"\x04Page\x18\x01 \x01(\v2\x0e.database.PageR\x04Page\x12$\n" +
	"\x05Sorts\x18\x02 \x03(\v2\x0e.database.SortR\x05Sorts\x12*\n" +
	"\aFilters\x18\x03 \x03(\v2\x10.database.FilterR\aFiltersB$Z\"github.com/Compogo/db-client/protob\x06proto3"

var (
	file_db_client_proto_models_proto_rawDescOnce sync.Once
	file_db_client_proto_models_proto_rawDescData []byte
)

func file_db_client_proto_models_proto_rawDescGZIP() []byte {
	file_db_client_proto_models_proto_rawDescOnce.Do(func() {
		file_db_client_proto_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_client_proto_models_proto_rawDesc), len(file_db_client_proto_models_proto_rawDesc)))
	})
	return file_db_client_proto_models_proto_rawDescData
}

var file_db_client_proto_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_db_client_proto_models_proto_goTypes = []any{
	(*Page)(nil),       // 0: database.Page
	(*Sort)(nil),       // 1: database.Sort
	(*Filter)(nil),     // 2: database.Filter
	(*Request)(nil),    // 3: database.Request
	(SortDirection)(0), // 4: database.SortDirection
	(Comparable)(0),    // 5: database.Comparable
}
var file_db_client_proto_models_proto_depIdxs = []int32{
	4, // 0: database.Sort.Direction:type_name -> database.SortDirection
	5, // 1: database.Filter.Comparable:type_name -> database.Comparable
	0, // 2: database.Request.Page:type_name -> database.Page
	1, // 3: database.Request.Sorts:type_name -> database.Sort
	2, // 4: database.Request.Filters:type_name -> database.Filter
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_db_client_proto_models_proto_init() }
func file_db_client_proto_models_proto_init() {
	if File_db_client_proto_models_proto != nil {
		return
	}
	file_db_client_proto_sort_direction_proto_init()
	file_db_client_proto_comparable_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_client_proto_models_proto_rawDesc), len(file_db_client_proto_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_client_proto_models_proto_goTypes,
		DependencyIndexes: file_db_client_proto_models_proto_depIdxs,
		MessageInfos:      file_db_client_proto_models_proto_msgTypes,
	}.Build()
	File_db_client_proto_models_proto = out.File
	file_db_client_proto_models_proto_goTypes = nil
	file_db_client_proto_models_proto_depIdxs = nil
}
